"""empty message

Revision ID: 0f26f87f4702
Revises: 
Create Date: 2020-01-15 16:44:20.595750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f26f87f4702'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('cut_off_points', sa.Integer(), nullable=False),
    sa.Column('number_of_students', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('aggregate', sa.Integer(), nullable=False),
    sa.Column('first_choice', sa.Integer(), nullable=False),
    sa.Column('second_choice', sa.Integer(), nullable=False),
    sa.Column('third_choice', sa.Integer(), nullable=False),
    sa.Column('fourth_choice', sa.Integer(), nullable=False),
    sa.Column('is_assigned', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_choice'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fourth_choice'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['second_choice'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['third_choice'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('school')
    # ### end Alembic commands ###
